### ISSUE TITLE
Supporting the developers: we have a Reddit community of over 1 million Dogecoin enthusiasts and we want to see what we can do to help you developers with your improvements to Dogecoin.

### ISSUE THREAD

**Issue by Iron-Legion-007** [rosetta-dogecoin/rosetta-dogecoin#22]
Can you let us know what are the best ways to help support you all? We have an engaged community and are willing to do what it takes to help. We aren't all that technical but let us know how we can help you.

**Comment by patricklodder** [comment]
Thanks, this is the rosetta-dogecoin project though. You've already found the "how to help" topic in discussions here. For generic Dogecoin development support and questions, please use https://reddit.com/r/dogecoindev.
