### ISSUE TITLE
Golang package renaming

### ISSUE THREAD

**Issue by patricklodder** [rosetta-dogecoin/rosetta-dogecoin#3]
Package needs to be renamed to reflect this library in `go.mod` and `Makefile`

Perhaps it's an idea for now to just leave all the internals pointed to the 
coinbase/rosetta-bitcoin library until something needs to get touched, and 
only at that point, we change it to local. This should lead to this repo being 
a lean delta to upstream.

**Comment by xanimo** [comment]
Keep us posted on when you'd like this changed.  I can do this one.

**Comment by patricklodder** [comment]
There's no better time than right now. I'll assign this to you, and await PR ❤️

**Comment by patricklodder** [comment]
Fixed with #10
