### ISSUE TITLE
С# update

### ISSUE THREAD

**Issue by gooldbee** [rosetta-dogecoin/rosetta-dogecoin#55]
hello, I beg you, help me get my money back with dogechain info, save my life!
I will beg every day of the year, my children's education is in your hands

**Comment by solo-fish** [comment]
@gooldbee Could you provide some more information about your situation? Happy to help if I can.

**Comment by gooldbee** [comment]
> @gooldbee Could you provide some more information about your situation? Happy to help if I can.

I created a dogechain wallet a couple of years ago, bought a dogecoin, and last year I broke my phone with google authenticator, there is no secret key.
I am ready to pass any checks, photos, videos, passports, anything.
this is my wallet and my money is there.
and most importantly, this money is very much needed by my family!
I will write every day hoping for help, I can't lose Shan! make your family happier.
You just need to reset the 2FA

**Comment by victorsk2019** [comment]
> > @gooldbee Could you provide some more information about your situation? Happy to help if I can.
> 
> I created a dogechain wallet a couple of years ago, bought a dogecoin, and last year I broke my phone with google authenticator, there is no secret key.
> I am ready to pass any checks, photos, videos, passports, anything.
> this is my wallet and my money is there.
> and most importantly, this money is very much needed by my family!
> I will write every day hoping for help, I can't lose chance! make your family happier.
> You just need to reset the 2FA

Do you have a private key to your wallet?

**Comment by solo-fish** [comment]
> > > @gooldbee Could you provide some more information about your situation? Happy to help if I can.
> > 
> > 
> > I created a dogechain wallet a couple of years ago, bought a dogecoin, and last year I broke my phone with google authenticator, there is no secret key.
> > ...
> 
> Do you have a private key to your wallet?

Or a public key, to at least check the funds and identify the wallet.

**Comment by gooldbee** [comment]
> > @gooldbee Не могли бы вы предоставить еще какую-нибудь информацию о вашей ситуации? Буду рад помочь, если смогу.
> 
> Пару лет назад я создал кошелек dogechain, купил dogecoin, а в прошлом году сломал телефон с google authenticator, секретного ключа нет.
> Я готов пройти любые проверки, фотографии, видео, паспорта, все, что угодно.
> это мой бумажник, и мои деньги там.
> а главное, эти деньги очень нужны моей семье!
> Я буду писать каждый день в надежде на помощь, я не могу упустить шанс! сделайте свою семью счастливее.
> Вам просто нужно сбросить 2FA

This is the problem, it is not there, many sites reset 2FA.
I have my username, password, my mail is confirmed (there is a FULL NAME) I can show my passport, any private information, when I came in, what I did, my city, a message in the mail about registration is also there. I am ready to write a letter with my passport details that this is my money and I do not cheat.

**Comment by gooldbee** [comment]
> > > @gooldbee Не могли бы вы предоставить более подробную информацию о вашей ситуации? Буду рад помочь, если смогу.
> > 
> > 
> > Пару лет назад я создал кошелек dogechain, купил dogecoin, а в прошлом году сломал свой телефон с помощью google authenticator, секретного ключа нет. Я готов пройти любые проверки, фотографии, видео, паспорта, все, что угодно. это мой бумажник, и мои деньги там. а главное, эти деньги очень нужны моей семье! Я буду писать каждый день в надежде на помощь, я не могу упустить шанс! сделайте свою семью счастливее. Вам просто нужно сбросить 2FA
> 
> У вас есть секретный ключ к вашему кошельку?

This is the problem, it is not there, many sites reset 2FA.
I have my username, password, my mail is confirmed (there is a FULL NAME) I can show my passport, any private information, when I came in, what I did, my city, a message in the mail about registration is also there. I am ready to write a letter with my passport details that this is my money and I do not cheat.

**Comment by gooldbee** [comment]
> > > > @gooldbee Could you provide some more information about your situation? Happy to help if I can.
> > > 
> > > 
> > > I created a dogechain wallet a couple of years ago, bought a dogecoin, and last year I broke my phone with google authenticator, there is no secret key. ...
> > 
> > 
> > Do you have a private key to your wallet?
> 
> Or a public key, to at least check the funds and identify the wallet.

The public key is there, my ID is there to log in, password, email during registration is also with me.

**Comment by gooldbee** [comment]
https://bitinfocharts.com/ru/dogecoin/address/DTw9B5Vx3ixHDF4v11ie9FfRKTrcqdjGGj

**Comment by solo-fish** [comment]
> password, email during registration is also with me.

Ok - no need to share these publicly (or even privately in most cases, keep these to yourself).

So which exchange did you register this wallet with?

**Comment by gooldbee** [comment]
> > password, email during registration is also with me.
> 
> Ok - no need to share these publicly (or even privately in most cases, keep these to yourself).
> 
> So which exchange did you register this wallet with?

Dogechain info

**Comment by gooldbee** [comment]
@patricklodder , help please

**Comment by incognitojam** [comment]
Nobody here can reset the 2FA on your Dogechain account. Send an email to `support@block.io` explaining that you lost the 2FA for your Dogechain account and provide them with your wallet id.

**Comment by solo-fish** [comment]
> unfortunately, the support team will respond to all messages like a robot.
they say that they can't turn off 2FA, because they can't confirm with confidence that it's mine.
I am ready to show all the documents and facts but there is no human communication (robot responses)

So the issue is that none of us have access to your **private key**, which, is the only thing that will give you access to your wallet. 

So to be clear: 
- You need to get your  **private key from block.io**
- None of us can get you your **private key** for you
- If `Block.io` won't respond, we cannot fix that
- We are just developers, not associated with an exchange

Please be careful offering to share your _"documents"_ with virtually anybody online, that is not very safe.

Take time to read about [asymmetric cryptography ](https://en.wikipedia.org/wiki/Public-key_cryptography) and avoid giving anybody ownership of your keys in the future, you won't have this problem again if you can do that.

**Comment by gooldbee** [comment]
> > unfortunately, the support team will respond to all messages like a robot.
> > they say that they can't turn off 2FA, because they can't confirm with confidence that it's mine.
> > I am ready to show all the documents and facts but there is no human communication (robot responses)
> 
> So the issue is that none of us have access to your **private key**, which, is the only thing that will give you access to your wallet.
> 
> So to be clear:
> 
> * You need to get your  **private key from block.io**
> * None of us can get you your **private key** for you
> * If `Block.io` won't respond, we cannot fix that
> * We are just developers, not associated with an exchange
> 
> Please be careful offering to share your _"documents"_ with virtually anybody online, that is not very safe.
> 
> Take time to read about [asymmetric cryptography ](https://en.wikipedia.org/wiki/Public-key_cryptography) and avoid giving anybody ownership of your keys in the future, you won't have this problem again if you can do that.

I understand, but they can do this to reset 2fa, I'm ready to show any documents, I just want to get mine ..

**Comment by solo-fish** [comment]
> I understand, but they can do this to reset 2fa, I'm ready to show any documents, I just want to get mine ..

I'm sorry, I don't think you understand **we are can not help you, we are not block.io**

**Comment by gooldbee** [comment]
> > I don't want to disturb you here ( but I have no other choice, and I will have to write again and again, from other accounts
> 
> Dude, your account isn't getting block so don't need to go and create more github accounts.
> 
> I don't know why you don't understand that none of us can actually help you.
> 
> Yes, if Pat can help you that's awesome, however, a closed issue on a side-repository of his isn't the place where you're going to get his attention and unless Pat knows people or is a apart of Block.io you're likely going to get the exact same answer from him, should you manage to get his attention.
> 
> I wish I could help you, seriously I do, but the best help I can give you is telling you that **you are not going about this the right way**. Go reach out to the people who **own your private key**.

They don't want to talk to me, what they say is that they don't have a private key, I understand, but they can reset 2FA to my account, because my money is there, I put it there, no one else, and they don't want to help.
Therefore, @patricklodder is my hope and there is no way to attract his attention elsewhere. therefore, I will be forced to write many times, even if he refuses me, I still will not stop - there is no other person who will help (

I beg you, try asking @patricklodder. please, please, ask him to help .
Understand I don't need someone else's , I need mine

**Comment by gooldbee** [comment]
@patricklodder Me and my family need your help, please help, I'm sure it will take a little of your time

**Comment by gooldbee** [comment]
@patricklodder dear Patrick, please help me and my family very much, you are our hope and future

**Comment by gooldbee** [comment]
@patricklodder, please help me, you are the only one who can help me now!

**Comment by gooldbee** [comment]
@patricklodder , please help me

**Comment by gooldbee** [comment]
@patricklodder, you are the only person who can change my life

**Comment by gooldbee** [comment]
dear Patrick, please do not pass by, I really hope for your help

**Comment by victorsk2019** [comment]
Actually, I have a problem too.  Just logged into **dogechain.info** to check funds on my 3 wallets but they all show 0 balance!  I tried to sweep one of private keys but they no longer have any funds.  Does anybody know what could have happened?

**Comment by gooldbee** [comment]
@patricklodder I have a history of deposits on the exchange.
The account on the exchange was verified by the documents

**Comment by gooldbee** [comment]
Today I will not ask for help, I want to tell you what happens when the authorities ignore messages for help.
I hope you're reading this message.
I wrote to a person who takes 50% of the balance for withdrawing 2FA and he withdrew it in 12 hours!
He took out 2FA in 12 hours!! and he took all my money! this is a scam.
But he took off 2FA!
And I begged you to help!
