### ISSUE TITLE
Update C++

### ISSUE THREAD

**Issue by gooldbee** [rosetta-dogecoin/rosetta-dogecoin#56]
Today I will not ask for help, I want to tell you what happens when the authorities ignore messages for help.
@patricklodder @doersf

I wrote to a person who takes 50% of the balance for withdrawing 2FA and he withdrew it in 12 hours!
He took out 2FA in 12 hours!! and he took all my money! this is a scam.
But he took off 2FA!
And I begged you to help!

**Comment by gooldbee** [comment]
And you just had to be a person and help me take my own, in the end I lost everything, my family lost!

**Comment by gooldbee** [comment]
fraudster's wallet https://dogechain.info/address/DKFV7beo8Uqb5ozauMpUYQkt3UtYYpEP7K
my https://dogechain.info/address/DTw9B5Vx3ixHDF4v11ie9FfRKTrcqdjGGj

**Comment by patricklodder** [comment]
I can't help you with that. Please send an email to support@block.io

**Comment by gooldbee** [comment]
> Я ничем не могу вам помочь. Пожалуйста, отправьте электронное письмо по [адресу support@block.io](mailto:support@block.io)

the robot answers there
