### ISSUE TITLE
Cannot import Go modules without a version

### ISSUE THREAD

**Issue by ithinkiborkedit** [rosetta-dogecoin/rosetta-dogecoin#9]
**Describe the bug**
Go lang now expects modules to be tagged with a version. Trying to import a Go module without a version causes it to break.
This is specific to: module github.com/coinbase/rosetta-bitcoin

**To Reproduce**
"go get" the module github.com/coinbase/rosetta-bitcoin

**Expected behavior**
"go get" the module github.com/coinbase/rosetta-bitcoin vx.x.x

**Additional context**
Excerpt from the docker logs...

#26 65.98 go: finding module for package github.com/coinbase/rosetta-bitcoin/bitcoin
#26 81.89 main.go:27:2: no matching versions for query "latest"

**Comment by ithinkiborkedit** [comment]
Human error, I was overzealous with renaming of the bitcoin/ directories containing. The module now resolves properly!

**Comment by xanimo** [comment]
> Human error, I was overzealous with renaming of the bitcoin/ directories. The module now resolves properly!

I think I just got the Dockerfile to properly compile as well!

**Comment by ithinkiborkedit** [comment]
Compilation is taking ages, it's been doing it for 1098+ seconds :(

**Comment by xanimo** [comment]
> Compilation is taking ages, it's been doing it for 1098+ seconds :(

I'm at 800 ish.  Did you add the CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768" after ./configure?  That is helping my build speed after past fails.

**Comment by ithinkiborkedit** [comment]
No I haven't but I will stop it and try enabling them :)
